Repository Bokmanee/bokmanee, pull requests merged in 2022-12, with the labels that each got.

#2 :truck: Feat : 라우터 설정
  src/App.tsx
Labels: page

#6 :sparkles: Feat : 스플래시 페이지 추가
  package-lock.json
  package.json
  public/assets/images/background.png
  src/pages/Splash.tsx
  src/sass/pages/_splash.scss
Labels: feature, page, style

#9 :sparkles: Feat : Input 아톰 구현
  src/atoms/Input.tsx
  src/sass/atoms/_input.scss
  src/sass/main.scss
  src/sass/pages/_splash.scss
Labels: element, feature, style

#12 :sparkles: Feat : 전체 레이아웃 스타일
  src/App.tsx
  src/components/AllLayout.tsx
  src/pages/Splash.tsx
  src/sass/layout/_allLayout.scss
  src/sass/main.scss
  src/sass/pages/_splash.scss
Labels: component, feature, page, style

#15 Feat/13/뒤로가기,튜토리얼,헤더
  src/atoms/Backspace.tsx
  src/atoms/BokClick.tsx
  src/atoms/Input.tsx
  src/components/Header.tsx
  src/sass/layout/_header.scss
Labels: component, feature

#17 :sparkles: Feat : 유저보드 구현
  src/atoms/Board.tsx
  src/pages/Splash.tsx
  src/pages/UserBoard.tsx
  src/sass/atoms/_board.scss
  src/sass/layout/_allLayout.scss
  src/sass/pages/_splash.scss
  src/sass/pages/_userBoard.scss
Labels: etc, feature, page, style

#20 :lipstick: Modify : 스플래시 수정
  src/pages/Splash.tsx
  src/sass/pages/_splash.scss
Labels: feature, page, style

#21 :sparkles: Feat: Button 아톰 구현
  .eslintrc.js
  package.json
  src/atoms/Button.tsx
  src/pages/Login.tsx
  src/sass/atoms/_button.scss
  src/sass/main.scss
  src/style.css
Labels: element, style

#23 :sparkles: Feat : 회원가입 페이지 마크업
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/sass/pages/_join.scss
Labels: feature, page, style

#24 :sparkles: Feat: 복주머니 아톰 마크업 작업
  src/atoms/BokPouch.tsx
  src/atoms/Button.tsx
  src/sass/atoms/_bokPouch.scss
  src/sass/atoms/_button.scss
  src/sass/layout/_flexLayout.scss
  src/sass/main.scss
Labels: element, style

#26 :lipstick: Add: 로그인페이지 마크업 구현
  src/pages/Login.tsx
  src/sass/pages/_login.scss
Labels: page, style

#30 :sparkles: Feat : 복주머니 선택
  src/atoms/Board.tsx
  src/pages/ChooseBok.tsx
  src/pages/UserBoard.tsx
  src/sass/atoms/_board.scss
  src/sass/layout/_header.scss
  src/sass/main.scss
  src/sass/pages/_chooseBok.scss
  src/sass/pages/_userBoard.scss
Labels: feature, page, style

#34 ✨ Feat: 비밀번호 찾기 페이지 마크업 구현
  src/pages/FindPassword.tsx
  src/sass/atoms/_input.scss
  src/sass/base/_reset.scss
  src/sass/main.scss
  src/sass/pages/_findPassword.scss
  src/sass/pages/_login.scss
Labels: page, style

#37 :lipstick: Modify : 복주머니 등록 마크업 수정
  src/atoms/Board.tsx
  src/pages/ChooseBok.tsx
  src/pages/RegisterBok.tsx
  src/pages/UserBoard.tsx
  src/sass/atoms/_board.scss
  src/sass/layout/_header.scss
  src/sass/main.scss
  src/sass/pages/_chooseBok.scss
  src/sass/pages/_userBoard.scss
Labels: feature, page, style

#40 :sparkles: Feat : 회원가입 후 완료 모달창 생성
  src/components/modal/JoinModal.tsx
  src/pages/Join.tsx
  src/sass/components/_joinModal.scss
Labels: feature, style

#41 :lipstick: Feat : 복만이 등록 완료 페이지
  src/App.tsx
  src/pages/RegisterBok.tsx
  src/pages/RegisterCompletion.tsx
  src/sass/main.scss
  src/sass/pages/_registerCompletion.scss
Labels: feature, page, style

#42 ✨ Feat: 파이어베이스 세팅
  .gitignore
  package.json
  src/firebase/config.ts
Labels: set

#47 :sparkles: Feat : 카카오 로그인 api 연결(토큰 생성)
  package-lock.json
  src/App.tsx
  src/components/KaKaoLogin.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/sass/pages/_join.scss
Labels: component, feature

#49 :sparkles: Feat : 카카오 로그인 후 닉네임 설정
  src/App.tsx
  src/components/KaKaoLogin.tsx
  src/components/modal/JoinModal.tsx
  src/pages/Login.tsx
  src/pages/NickNameSetting.tsx
Labels: component, feature

#51 ✨ Feat: 헤더 복만이 클릭시 튜토리얼 페이지로 이동
  src/components/Header.tsx
  src/pages/Tutorial.tsx
Labels: etc, page

#53 :lipstick: Modify: 커스텀 스크롤 파일 분기 및 전체적용
  src/components/Message.tsx
  src/pages/MyBoard.tsx
  src/sass/abstracts/_customScroll.scss
  src/sass/components/_message.scss
  src/sass/main.scss
  src/sass/pages/_myBoard.scss
Labels: style

#55 :sparkles: Feat: 공유하기모달 마크업
  src/components/modal/JoinModal.tsx
  src/components/modal/Modal.tsx
  src/components/modal/ShareModal.tsx
  src/pages/MyBoard.tsx
  src/sass/components/_joinModal.scss
  src/sass/components/_shareModal.scss
  src/sass/main.scss
Labels: component, feature, page, style

#56 :sparkles: Feat : firebase 회원가입
  src/App.tsx
  src/atoms/Input.tsx
  src/components/Message.tsx
  src/components/modal/JoinModal.tsx
  src/pages/ChooseBok.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/pages/MyBoard.tsx
  src/pages/RegisterBok.tsx
  src/pages/RegisterCompletion.tsx
  src/pages/UserBoard.tsx
Labels: feature

#60 ✨ Feat/46/로그인유효성(에러메세지 까지)
  src/atoms/BokClick.tsx
  src/components/Header.tsx
  src/pages/Login.tsx
  src/sass/main.scss
  src/sass/pages/_login.scss
Labels: page, style

#59 :sparkles: Feat : 구글 로그인 api 연동
  src/atoms/Button.tsx
  src/components/GoogleLogin.tsx
  src/components/KaKaoLogin.tsx
  src/pages/Login.tsx
Labels: component, feature

#62 :sparkles: Feat : firebase 메세지 내용 추가
  src/App.tsx
  src/atoms/BokPouch.tsx
  src/components/Message.tsx
  src/pages/ChooseBok.tsx
  src/pages/Login.tsx
  src/pages/MyBoard.tsx
  src/pages/ReceivedMsg.tsx
  src/pages/RegisterBok.tsx
  src/pages/RegisterCompletion.tsx
  src/pages/Splash.tsx
  src/pages/UserBoard.tsx
  src/pages/UserBoardPage.tsx
Labels: feature

#63 :lipstick: Modify : 구글 로그인 수정
  src/App.tsx
  src/components/GoogleLogin.tsx
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/pages/NickNameSetting.tsx
  src/sass/atoms/_button.scss
Labels: component, feature

#65 :sparkles: Feat : 구글계정과 닉네임 파이어베이스에 올리기
  src/App.tsx
  src/pages/Login.tsx
  src/pages/NickNameSetting.tsx
Labels: component, feature

#66 ✨ Feat: 링크 공유하기 기능 구현
  public/index.html
  src/pages/Login.tsx
  src/pages/MyBoard.tsx
  src/sass/pages/_join.scss
  src/types/react-app-env.d.ts
Labels: feature, style

#69 :poop: Add: 충돌나서 삭제됐던 코드 추가
  src/components/modal/ShareModal.tsx
Labels: bug

#73 :sparkles: Modify: 유효성 검사 후 로그인
  src/pages/Login.tsx
Labels: feature

#74 :sparkles: Feat: 비밀번호 재설정 이메일 전송 기능 구현
  src/pages/FindPassword.tsx
  src/sass/pages/_findPassword.scss
Labels: feature, style

#76 :sparkles: Add: 메세지 닫기 기능 구현
  src/pages/ReceivedMsg.tsx
Labels: feature, page

#78 ✨ Feat: 404페이지 구현
  public/assets/images/background-sad-rabbit.svg
  src/App.tsx
  src/pages/Error404.tsx
  src/sass/main.scss
  src/sass/pages/_error404.scss
Labels: feature, page, style
